## Access the Elements of an Array


In [1]:
num1= [10,20,30,40,50]
num2=[10.5,20.6,30.7,40.8,50.9]
names=["XYZ", "PQR", "ABC", "LMN"]
grades=['A','B','C','D','E']

In [3]:
print(num1[1])

20


In [4]:
print(num1[-1])

50


In [5]:
print(len(num2))

5


## Changing the Elements of an Array

In [6]:
num1= [10,20,30,40,50]
num2=[10.5,20.6,30.7,40.8,50.9]
names=["XYZ", "PQR", "ABC", "LMN"]
grades=['A','B','C','D','E']

In [7]:
num1[0]=100 #changing the elements of the array
print(num1)

[100, 20, 30, 40, 50]


In [8]:
num2.append(90.45)
print(num2)

[10.5, 20.6, 30.7, 40.8, 50.9, 90.45]


In [9]:
names.pop(2)
print(names)

['XYZ', 'PQR', 'LMN']


In [10]:
grades.pop(4)
print(grades)

['A', 'B', 'C', 'D']


## Removing elements of an array using del, remove() and pop()

In [16]:
color = ["violet", "indigo", "blue", "green", "yellow", "orange", "red"] 

In [17]:
del color[4]
print(color)

['violet', 'indigo', 'blue', 'green', 'orange', 'red']


In [18]:
color.remove("blue")
print(color)

['violet', 'indigo', 'green', 'orange', 'red']


In [19]:
color.pop(3)
print(color)

['violet', 'indigo', 'green', 'red']


## Built-in methods of array

In [21]:
num1= [10,20,30,40,50]
num2=[10.5,20.6,30.7,40.8,50.9]
names=["XYZ", "PQR", "ABC", "LMN"]
grades=['A','B','C','D','E']

In [22]:
num3 = num2.copy()
print(num3)

[10.5, 20.6, 30.7, 40.8, 50.9]


In [23]:
c = names.count("PQR")
print(c)

1


In [24]:
names.insert(1, "Hi")
print(names)

['XYZ', 'Hi', 'PQR', 'ABC', 'LMN']


In [25]:
grades.remove("C")
print(grades)

['A', 'B', 'D', 'E']


In [26]:
names.sort()
print(names)

['ABC', 'Hi', 'LMN', 'PQR', 'XYZ']


In [27]:
grades.reverse()
print(grades)

['E', 'D', 'B', 'A']


## Numpy

In [29]:
import numpy as arr
names = arr.array(["XYZ", "PQR", "ABC", "LMN"])
print(names)

['XYZ' 'PQR' 'ABC' 'LMN']


In [30]:
nums1=[10,20,30,40,50]
nums2=[60,70,80,90,100]
twodnum=arr.array([nums1, nums2])
print(twodnum)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [36]:
import numpy as np
l1=[10, 20, 30,70,50]
l2=[40, 50, 60,60,40]

In [37]:
arrA = np.array(l1)
arrB = np.array(l2)
arrC = arrA + arrB
print(arrC)

[ 50  70  90 130  90]


In [38]:
print(arrC[-2])

130


In [39]:
print(arrC[2:4])

[ 90 130]


## Lists

In [41]:
squares = [1, 4, 9, 16, 25]
squares

[1, 4, 9, 16, 25]

In [42]:
squares + [36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [45]:
# append() method 
cubes = [1, 8, 27, 65, 125]
cubes.append(216)
cubes

[1, 8, 27, 65, 125, 216]

In [48]:
cubes.append(7 ** 3)
cubes

[1, 8, 27, 65, 125, 216, 343, 343, 343]

In [50]:
letters = ['a', 'b', 'c', 'd']
len(letters)

4

In [52]:
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]
x = [['a', 'b', 'c'], [1, 2, 3]]
x[0]

['a', 'b', 'c']

In [53]:
x[0][1]

'b'

## strings

In [1]:
'ClassRoom'

'ClassRoom'

In [2]:
'doesnt\'t'

"doesnt't"

In [3]:
word = 'Python'
word[0]

'P'

In [4]:
word[-1]

'n'

In [5]:
word[:2]+word[2:]

'Python'

In [6]:
word[:4]+word[4:]

'Python'

In [7]:
word[:2]

'Py'

In [8]:
word[4:]      #characters from position 4 (included) to the end 

'on'

In [9]:
word[-2:]     #characters from the second-last(included) to the end

'on'